#!/usr/bin/env python3
"""Rebuild the checked-in Dali SFX arrays using ACME."""
import argparse
import pathlib
import subprocess
import shutil
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]


def generate(acme):
    acme = shutil.which(acme) or str(pathlib.Path(acme).resolve())
    lines = ['/* Generated by tools/build_sfx.py; see src/asm/sfx/README.md. */',
             '#ifndef KC_SFX_H', '#define KC_SFX_H']
    with tempfile.TemporaryDirectory(prefix='kc-sfx-') as directory:
        output = pathlib.Path(directory) / 'sfx.prg'
        source = pathlib.Path(directory) / 'dali_sfx.asm'
        source.write_bytes((ROOT / 'src/asm/sfx/dali_sfx.asm').read_bytes())
        for name, flags in (
            ('decruncher_small_effect', ['SFX_SMALL', 'SFX_EFFECT']),
            ('decruncher_effect', ['SFX_FAST', 'SFX_EFFECT']),
            ('decruncher_small', ['SFX_SMALL']),
            ('decruncher', ['SFX_FAST']),
        ):
            subprocess.run([acme, '-f', 'cbm', *['-D' + f + '=1' for f in flags],
                            '-o', str(output), str(source)],
                           check=True, cwd=directory)
            data = output.read_bytes()
            lines.append('static const unsigned char ' + name + '[] = {')
            for offset in range(0, len(data), 12):
                lines.append('    ' + ', '.join(f'0x{x:02x}' for x in data[offset:offset+12]) + ',')
            lines.append('};')
    return '\n'.join(lines + ['#endif', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--acme', default='acme')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate(args.acme)
    header = ROOT / 'src/sfx.h'
    if args.check:
        if header.read_text() != result:
            raise SystemExit('src/sfx.h is stale; run tools/build_sfx.py')
    else:
        header.write_text(result, encoding='ascii')
